import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        //ENGLISH LANGUAGE

        'en_US': {
          'hello': 'This is Hello',
          'All Order list': 'All Order List',
          'Wallet Balance': 'Wallet Balance',
          'View Records': 'View Records',
          'View': 'View',
          "Total Orders": "Total Orders",
          "Total Products": "Total Products",
          "Here goes the order list": "Here goes the order list",
          "Order Code": "Order Code",
          "Item Total Price": "Item Total Price",
          "Income": "Income",
          "Pickup & Delivery Info": "Pickup & Delivery Info",
          "Status Info": "Status Info",
          "Created At": "Created At",
          "Action": "Action",
          "Order": "Order",
          "Product": "Product",
          "Delivery": "Delivery",
          "Status": "Status",
          "Shop List": "Shop List",
          "Create Shop": "Create Shop",
          "Here goes the shop list": "Here goes the shop list",
          "Name": "Name",
          "Balance": "Balance",
          "Commission on per order": "Commission on per order",
          "Image": "Image",
          "Product Category Add/Edit": "Product Category Add/Edit",
          "Category Name": "Category Name",
          "No file selected": "No file selected",
          "Enter The category": "Enter The category",
          "Save": "Save",
          "Enter Active state": "Enter Active state",
          "Reset": "Reset",
          "Product List": "Product List",
          "Here goes the product list": "Here goes the product list",
          "Create Product": "Create Product",
          "No data available in the table": "No data available in the table",
          "Set Customer Range": "Set Customer Range",
          "Range Radius (Km)": "Range Radius (Km)",
          "Cancle": "Cancle",
          "Create New Product": "Create New Product",
          "Basic": "Basic",
          "Priching & Options": "Priching & Options",
          "Addons": "Addons",
          "Category": "Category",
          "Full Description": "Full Description",
          "Open Camera": "Open Camera",
          "Short Description": "Short Description",
          "option name ": "option name ",
          "Price": "Price",
          "Description": "Description",
          "Addon Add/Edit": "Addon Add/Edit",
          "Icon": "Icon",
          "Addon List": "Addon List",
          "Here goes the addon list": "Here goes the addon list",
          "Order List": "Order List",
          "Shop": "Shop",
          "Products": "Products",
          "All Orders": "All Orders",
          "Failed": "Failed",
          "New": "New",
          "Product Name": "Product Name",
          "Order Detail": "Order Detail",
          "Accept": "Accept",
          "Reject": "Reject",
          "Item name": "Item name",
          "Quantity": "Quantity",
          "Unit Price": "Unit Price",
          "Total": "Total",
          "Special Request": "Special Request",
          "Delivery Charge": "Delivery Charge",
          "Service Charge": "Service Charge",
          "Your Shop": "Your Shop",
          "Here goes the shop": "Here goes the shop",
          "Distance": "Distance",
          "Change Delivery Time":"Change Delivery Time",
        },
        'pt_PT': {
          "Icon": "Ícone",
          'Wallet Balance': 'Balanço da Carteira',
          'hello': 'hdeythsllio',
          'All Order List': 'Lista de todos os pedidos',
          "View Records": "Ver Registos",
          'View': 'Visão',
          "Total Orders": "Total encomendas",
          "Total Products": "Total produtos",
          "Here goes the order list": "Esta é a lista de encomendas",
          "Order Code": "Número da encomenda",
          "Item Total Price": "Preço total do item",
          "Income": "Rendimento",
          "Pickup & Delivery Info": "Info recolha e entrega",
          "Status Info": "Informações sobre o estado",
          "Created At": "Criado a",
          "Action": "Ação",
          "Order": "Encomenda",
          "Product": "Produto",
          "Active": "Ativo",
          "Inactive": "Inativo",
          "Super Admin": "Super Admin",
          "Customer": "Cliente",
          "Shop Owner": "Lojista",
          "Delivery Man": "Estafeta",
          "Pending": "Pendente",
          "Accepted": "Aceite",
          "Processing": "Em processamento",
          "Product Ready": "Produto pronto",
          "Picked": "Recolhido",
          "Delivered": "Entregue",
          "Cancelled": "Cancelado",
          "Rejected": "Rejeitado",
          "Confirmed": "Confirmado",
          "Arrived at Shop": "Chegou à loja",
          "On Transit": "Em transito",
          "Delivery": "Entrega",
          "Status": "Estado",
          "Shop List": "Lista de lojas",
          "Create Shop": "Criar loja",
          "Here goes the shop list": "Aqui pode ver a lista de lojas",
          "Name": "Nome",
          "Balance": "Saldo",
          "Commission on per order": "Comissão por encomenda",
          "Image": "Imagem",
          "Product Category Add/Edit": "Categoria de produto Adicionar/Editar",
          "Category Name": "Nome da categoria",
          "Active Status": "Estado ativo",
          "No file selected": "Nenhum arquivo selecionado",
          "Enter The category": "Entre na categoria",
          "Save": "Gravar",
          "Enter Active state": "Entre no estado ativo",
          "Reset": "Reiniciar",
          "Product List": "Lista de produtos",
          "Here goes the product list": "Esta é a lista de produtos",
          "Create Product": "Criar produto",
          "No data available in the table": "Sem dados disponíveis na tabela",
          "Set Customer Range": "Definir raio de clientes",
          "Range Radius (Km)": "Intervalo de Raio (km)",
          "Cancle": "Cancelar",
          "New": "Novo",
          "Create New Product": "Criar novo produto",
          "Basic": "Info Básica",
          "Priching & Options": "Opções e preços",
          "Addons": "Extras",
          "Category": "Categoria",
          "Full Description": "Descrição longa",
          "Open Camera": "Câmera Aberta",
          "Short Description": "Descrição curta",
          "option name ": "Nome da opção",
          "Price": "Preço",
          "Is Default?": "Está predefinido?",
          "Description": "Descrição",
          "Addon Add/Edit": "Adicionar/Editar extras",
          "Addon List": "Lista de extras",
          "Here goes the addon list": "Esta é a lista de addon",
          "Order List": "Lista de Encomendas",
          "Shop": "Loja",
          "Products": "Produtos",
          "All Orders": "Todas as encomendas",
          "Failed": "Falhado",
          "Product Name": "Nome do produto",
          "Order Detail": "Detalhes da encomenda",
          "Accept": "Aceitar",
          "Reject": "Rejeitar",
          "Item name": "Nome do produto",
          "Quantity": "Quantidade",
          "Unit Price": "Preço unitário",
          "Total": "Total",
          "Special Request": "Pedido especial",
          "Delivery Charge": "Taxa de entrega",
          "Service Charge": "Taxa de serviço",
          "Item Total": "Total do produto",
          "Delivery Info": "Info entrega",
          "Pickup": "Recolha",
          "Track Order": "Seguir encomenda",
          "Order Placed": "Encomenda criada",
          "Track Delivery Man": "Seguir estafeta",
          "Customer Delivery Info": "Info entrega ao cliente",
          "Address": "Morada",
          "Contact Number": "Número de Contacto",
          "Phone": "Telefone",
          "Order Note": "Nota da encomenda",
          "Delivery Started": "A entrega começou",
          "Delivery not on time": "Não entregue a tempo",
          "Delivery on time": "Entregue a tempo",
          "Assign Delivery Man": "Designar estafeta",
          "Groups": "Grupos",
          "Sub Categories": "Sub-categorias",
          "Latitude": "Latitude",
          "Longitude": "Longitude",
          "Country": "País",
          "State": "Distrito",
          "City": "Cidade",
          "Postal Code": "Código postal",
          "Go to Current Location": "Ir para a localização atual",
          "Add Holidays": "Adicionar férias",
          "Select Holidays": "Selecionar férias",
          "Holiday List": "Lista de feriados",
          "Here goes the holiday list": "Esta é a lista de feriados",
          "Date": "Data",
          "Meta Title": "Título Meta",
          "Meta Keywords": "Palavras-chave Meta",
          "Meta Descriptions": "Descrições Meta",
          "Days": "Dias",
          "Weekend": "Fim de semana",
          "Opening": "Abertura",
          "Break Start": "Fecho intermédio",
          "Break End": "Abertura intermédia",
          "Closing": "Encerramento",
          "Reviewer": "Avaliador",
          "Review": "Avaliação",
          "Rating": "Rating",
          "Contact & Address": "Contacto & Endereço",
          "Schedule": "Horario",
          "Holidays": "Férias",
          "Your Shop": "Sua loja",
          "Here goes the shop": "Aqui vai a loja",
          "Distance": "Distância",
          "Change Delivery Time":"Alterar tempo de entrega"
        }
      };
}


// {
//     "Payment Not Done": "Pagamento não efetuado",
//     "Waiting for payment": "A aguardar pagamento",
//     "Payment Complete": "Pagamento completo",
//     "Payment Cancelled": "Pagamento cancelado",
//     "Active": "Ativo",
//     "Inactive": "Inativo",
//     "Super Admin": "Super Admin",
//     "Customer": "Cliente",
//     "Shop Owner": "Lojista",
//     "Delivery Man": "Estafeta",
//     "Pending": "Pendente",
//     "Accepted": "Aceite",
//     "Processing": "Em processamento",
//     "Product Ready": "Produto pronto",
//     "Picked": "Recolhido",
//     "Delivered": "Entregue",
//     "Cancelled": "Cancelado",
//     "Rejected": "Rejeitado",
//     "Confirmed": "Confirmado",
//     "Arrived at Shop": "Chegou à loja",
//     "On Transit": "Em transito",
//     "Data retrieved successfully.": "Dados extraídos com sucesso",
//     "Something went wrong.": "Algo correu mal",
//     "The date is from past.": "Esta data já passou",
//     "The date is too far in future.": "Esta data está demasiado longe.",
//     "Today is holiday.": "Hoje é feriado",
//     "Shop is close.": "Loja está fechada",
//     "Shop is open.": "Loja está aberta",
//     "User not found.": "Utilizador não encontrado",
//     "User already active.": "Utilizador já está ativo",
//     "Email sent successfully.": "E-mail enviado com sucesso.",
//     "New Password must be consist of Uppercase, Lowercase , Number and Special character.": "A Nova Password deve conter letras maiúsculas, minúsculas, números e caracteres especiais.",
//     "User logout successful": "Logout do utilizador bem-sucedido",
//     "User logout unsuccessful": "Logout do utilizador sem sucesso",
//     "Profile data retrieved.": "Dados do perfil extraídos.",
//     "Invalid shop": "Loja inválida",
//     "Not assigned yet.": "Ainda não atribuído",
//     "Invalid product.": "Produto inválido",
//     "Invalid category.": "Categoria inválida",
//     "Invalid shop.": "Loja inválida",
//     "Set Commission on per order (%)": "Definir comissão por encomenda (%)",
//     "Set Commission": "Definir comissão",
//     "Suspended": "Suspenso",
//     "Blocked": "Bloqueado",
//     "Set Commission per KM (in currency amount)": "Definir comissão por KM (em valor)",
//     "Invalid user.": "Utilizador inválido",
//     "Yor are not authorized.": "Não tem autorização",
//     "Your account is inactive. Please change your password or contact with admin.": "A sua conta está inativa. Por favor, mude a password ou contacte o admin",
//     "You are blocked. Contact with admin.": "Está bloqueado. Contacte o admin.",
//     "Your Account has been suspended. Please contact with admin to active again!": "A sua conta foi suspensa. Por favor, contacte com o admin para ativar de novo!",
//     "Something went wrong!": "Algo correu mal!",
//     "Request from invalid application.": "Pedido de uma aplicação inválida.",
//     "You are suspended. Contact to support.": "Está suspenso. Contacte para apoio.",
//     "Your account is not active.": "A sua conta não está ativa.",
//     "Weired case": "Caso Estranho",
//     "Reset Password": "Reiniciar password",
//     "Name field is required.": "O campo do Nome é obrigatório.",
//     "Name can\\'t be more than 100 character.": "O nome não pode ter mais de 100 caracteres.",
//     "Slug field is required.": "O slug é obrigatório",
//     "Invalid status.": "Estado inválido",
//     "Restaurant is required.": "Restaurante é obrigatório",
//     "Price is required.": "Preço é obrigatório",
//     "Invalid Price.": "Preço inválido",
//     "Price must be greater than 0.00": "Preço deve ser maior que 0.00",
//     "Invalid role.": "Função inválida.",
//     "Invalid register type.": "Registo inválido.",
//     "First Name field can not be empty": "Primeiro nome não pode estar vazio",
//     "Last Name field can not be empty": "Último nome não pode estar vazio",
//     "Password field can not be empty": "Password não pode estar vazio",
//     "Email field can not be empty": "O campo do email não pode estar vazio",
//     "Email Address already exists": "Este endereço de email já existe",
//     "Invalid email address": "Endereço de email inválido",
//     "Phone Address already exists": "Este contacto já existe",
//     "Password must be consist of Uppercase, Lowercase , Number and Special character.": "A Password deve conter letras maiúsculas, minúsculas, números e caracteres especiais.",
//     "Old Password field can not be empty!": "Campo da Password antiga não pode estar vazio!",
//     "New Password field can not be empty!": "Campo da Password nova não pode estar vazio!",
//     "New Password length must be minimum 6 characters!": "Campo da Password deve ter no mínimo 6 caracteres!",
//     "Password not matched with confirm password!": "A Password não corresponde com a password confirmada!",
//     "Confirm password field can not be empty!": "Campo Confirmar Password não pode estar vazio!",
//     "First Name field is required.": "O campo do Primeiro Nome é obrigatório.",
//     "First Name can\\'t be more than 100 character.": "O Primeiro Nome não pode ter mais de 100 caracteres.",
//     "Last Name field is required.": "O campo do Último Nome é obrigatório.",
//     "Last Name can\\'t be more than 100 character.": "O Último Nome não pode ter mais de 100 caracteres.",
//     "Email can not be empty!": "Email não pode estar vazio!",
//     "Email address already exists!": "Este endereço de email já existe!",
//     "Invalid email format!": "Formato de email inválido",
//     "Phone can not be empty!": "Número de Telemóvel não pode estar vazio!",
//     "Phone number already exists!": "Este número de telemóvel já existe!",
//     "Email field can not be empty!": "O campo de Email não pode estar vazio!",
//     "Invalid email!": "Email inválido!",
//     "Module can\\'t be empty!": "Módulo não pode estar vazio!",
//     "Role can\\'t be empty!": "Função não pode estar vazio!",
//     "Status field is required.": "O campo de Estado é obrigatório.",
//     "Password field can not be empty!": "O campo de password não pode estar vazio!",
//     "Email or phone field can not be empty!": "O campo de email ou número de telemóvel não pode estar vazio!",
//     "User get successfully!": "",
//     "Wrong credentials!. For phone enter full phone number with +countrycode": "Credenciais erradas!. Para telemóvel introduir o número de telemóvel completo com o +indicativo do país",
//     "Your account is inactive. Please verify your email. ": "A sua conta está inativa. Por favor, verifique o seu email.",
//     "Click here to resend verification email": "Carregue aqui para reenviar o email de verificação",
//     "Your account is inactive. Please verify your email.": "A sua conta está inativa. Por favor, verifique o seu email.",
//     "Successfully registered. An email has been sent, please verify.": "Registado com sucesso. Foi enviado um email, por favor verifique.",
//     "Invalid user code.": "Código de utilizador inválido.",
//     "Email verified. Now try to log in.": "Email verificado. Tente fazer login agora.",
//     "An email has been sent. Please check.": "Foi enviado um email. Por favor, verifique.",
//     "Invalid link.": "Link inválido.",
//     "Link valid.": "Link válido.",
//     "Invalid code.": "Código inválido.",
//     "Password reset successfully.": "Redefinição da password foi bem-sucedida",
//     "The shop is not available. Your cart is empty.": "A loja não está disponível. O carrinho está vazio.",
//     "Invalid product": "Produto inválido",
//     "Product added to cart successfully.": "Produto adicionado ao carrinho com sucesso.",
//     "Product updated to cart successfully.": "Produto atualizado no carrinho com sucesso.",
//     "Product deleted from cart successfully.": "Produto removido do carrinho com sucesso.",
//     "Product addon added to cart successfully.": "Extra adicionado ao carrinho com sucesso.",
//     "Addon updated to cart successfully.": "Addon atualizado no carrinho com sucesso.",
//     "View details": "Ver detalhes",
//     "Accept": "Aceitar",
//     "Reject": "Rejeitar",
//     "Processing?": "Em processamento?",
//     "Product Ready?": "Produto pronto?",
//     "Order placed successfully.": "Encomenda efetuada com sucesso",
//     "Unfortunately! Your cart is empty.": "Infelizmente, o seu carrinho está vazio!",
//     "Restaurant can\\'t process your order at your expected delivery time.": "O Restaurante não consegue processar o seu pedido na hora de entrega estimada.",
//     "Invalid delivery time slot.": "Horário de entrega inválido.",
//     "Invalid pickup time slot": "Horário de recolha inválido.",
//     "Status updated successfully.": "Estado atualizado com sucesso.",
//     "Invalid Order or Status.": "Estado ou Encomenda inválido.",
//     "Your request is under processing.": "O seu pedido está a ser processado.",
//     "Invalid request.": "Pedido inválido.",
//     "Sorry!!. Delivery man already assigned.": "Desculpe!! Estafeta já atribuído.",
//     "Order accepted successfully.": "Encomenda aceite com sucesso",
//     "Order deleted successfully.": "Encomenda eliminada com sucesso",
//     "Order delete failed.": "Eliminação da encomenda sem sucesso.",
//     "Payment Option has been created successfully.": "Opção de pagamento foi criada com sucesso.",
//     "Payment Option create failed.": "Criação da apção de pagamento sem sucesso.",
//     "Payment Option has been updated successfully": "Opção de pagamento atualizada com sucesso.",
//     "Profile updated successfully.": "Perfil atualizado com sucesso.",
//     "Profile update failed.": "Atualização do perfil sem sucesso.",
//     "Password updated successfully.": "Password atualizada com sucesso.",
//     "Password update failed.": "Atualização da password sem sucesso.",
//     "Incorrect old password!.": "Password antiga incorreta!.",
//     "Unique and valid Slug required": "Slug único e válido obrigatório",
//     "Valid Slug": "Slug válido",
//     "Cuisine has been created successfully.": "Cozinha foi criada com sucesso.",
//     "Cuisine create failed.": "Criação da cozinha sem sucesso.",
//     "Cuisine has been updated successfully": "Cozinha foi atualizada com sucesso.",
//     "Cuisine deleted successfully.": "Cozinha foi eliminada com sucesso.",
//     "Cuisine delete failed.": "Cozinha foi eliminada sem sucesso.",
//     "Addon has been created successfully.": "Extra criado com sucesso.",
//     "Addon create failed.": "Criação do extra sem sucesso.",
//     "Addon has been updated successfully": "Extra atualizado com sucesso.",
//     "Addon deleted successfully.": "Extra eliminado com sucesso.",
//     "Category has been created successfully.": "Categoria criada com sucesso",
//     "Category has been updated successfully": "Categoria atualizada com sucesso",
//     "Category deleted successfully.": "Categoria eliminada com sucesso",
//     "Category delete failed.": "Eliminação da categoria sem sucesso",
//     "Category order updated successfully.": "Categoria da encomenda atualizada com sucesso.",
//     "Category order update failed.": "Atualização da categoria da encomenda sem sucesso.",
//     "This is default option.": "Isto é uma opção predefinida.",
//     "Product has been created successfully.": "O Produto foi criado com sucesso.",
//     "Product create failed.": "Criação do produto sem sucesso.",
//     "Product has been updated successfully": "O Produto foi atualizado com sucesso.",
//     "Pricing saved successfully.": "Preços afixados com sucesso.",
//     "Invalid product option.": "Opção de Produto inválida.",
//     "Option saved successfully.": "Opção guardada com sucesso.",
//     "Option deleted successfully.": "Opção eliminada com sucesso.",
//     "Max gallery image limit reached.": "Limite máximo de imagens na galeria atingido.",
//     "Image uploaded successfully": "Imagem carregada com sucesso.",
//     "Image deleted successfully.": "Imagem eliminada com sucesso.",
//     "Invalid delete request.": "Pedido de eliminação de imagem inválido.",
//     "Product deleted successfully.": "Produto eliminado com sucesso.",
//     "Product delete failed.": "Eliminação do produto sem sucesso.",
//     "Supplement has been created successfully.": "O Suplemento foi criado com sucesso.",
//     "Supplement create failed.": "A criação do suplemento não foi bem sucedida.",
//     "Supplement has been updated successfully": "O suplemento foi atualizado com sucesso.",
//     "Supplement deleted successfully.": "Suplemento eliminado com sucesso.",
//     "Supplement delete failed.": "Eliminação do suplemento sem sucesso.",
//     "Category create failed.": "Criação da categoria sem sucesso.",
//     "Shop has been created successfully.": "A loja foi criada com sucesso.",
//     "Shop create failed.": "Criação da loja sem sucesso.",
//     "Invalid Shop": "Loja inválida",
//     "Shop has been updated successfully": "A loja foi atualizada com sucesso",
//     "Schedule saved successfully.": "Horário guardado com sucesso.",
//     "Holidays saved successfully.": "Feriados atualizados com sucesso.",
//     "Invalid date": "Data inválida",
//     "Meta info saved successfully.": "Informação Meta guardada com sucesso.",
//     "Commission set successfully.": "Comissões definidas com sucesso.",
//     "Shop deleted successfully.": "Loja eliminada com sucesso.",
//     "Shop delete failed.": "Elminação da loja sem sucesso.",
//     "Successful": "Bem-sucedido",
//     "Something went wrong": "Algo correu mal",
//     "Role permission has been updated successfully": "Permissão da função atualizada com sucesso",
//     "Role create failed": "Criação da função sem sucesso",
//     "Role has been created successfully": "Função criada com sucesso",
//     "Role has been updated successfully": "Função atualizada com sucesso",
//     "Routing List synced successfully.": "Lista de roteamento sincronizada com sucesso.",
//     "Routing List sync failed.": "Sincronização da lista de roteamento sem sucesso.",
//     "Setting saved successfully.": "Configuração guardada com sucesso.",
//     "Setting saved failed.": "Guardar a configuração sem sucesso.",
//     "Faqs updated successfully.": "Faqs atualizado com sucesso.",
//     "Faqs update failed.": "Atualização das Faqs sem sucesso.",
//     "Faqs created successfully.": "Faqs criadas com sucesso.",
//     "Faqs create failed.": "Criação das Faqs sem sucesso.",
//     "Faqs deleted successfully.": "Faqs eliminadas com sucesso.",
//     "Faqs delete failed.": "Eliminação das faqs sem sucesso.",
//     "Order updated successfully.": "Encomenda atualizada com sucesso.",
//     "User been created successfully. Initial Password: 123456": "Utilizador criado com sucesso. Password inicial: 123456",
//     "User create failed.": "Criação do utilizador sem sucesso.",
//     "User has been updated successfully": "O utilizador foi atualizado com sucesso",
//     "Page not found": "Página não encontrada",
//     "Sorry, but the page you are looking for has not been found. Try checking the URL for error, then hit the refresh button on your browser or try to find something else in our app.": "    Lamentamos, a página que procura já não se encontra disponível. Verifique se o URL tem erros, depois carregue no botão de atualização no seu browser e tente encontrar outra coisa na sua aplicação.",
//     "Return to ": "Devolver a",
//     "Home": "Home",
//     "Whoops! Permission denied": "Ups! Permissão negada",
//     "It\\'s looking like you may have taken a wrong turn.You have no permission of this page.Do you want to go to dashboard ?": "Parece que se enganou. Não tem permissão para esta página. Quer ir para a dashboard?",
//     "Back to Dashboard": "Regressar à Dashboard",
//     "Order": "Encomenda",
//     "Product": "Produto",
//     "Settings": "Definições",
//     "Set Commission Rate": "Definir taxa de comissão",
//     "General Settings": "Configurações gerais",
//     "Web Contents": "Conteúdos web",
//     "Terms & Condition": "Termos e condições",
//     "Privacy Policy": "Politica de privacidade",
//     "FAQs": "FAQs",
//     "About Us": "Sobre nós",
//     "Why Choose Us": "Porquê nós?",
//     "Shop": "Loja",
//     "Auction": "Leilão",
//     "Brands": "Marcas",
//     "Tags": "Tags",
//     "Combination Type": "Tipo de Combinação",
//     "Combination": "Combinação",
//     "Messaging": "Mensagens",
//     "Users": "Utilizadores",
//     "Shop Management": "Gestão de loja",
//     "Product Management": "Gestão de produto",
//     "Order Management": "Gestão de encomenda",
//     "Profile Settings": "Definições do perfil",
//     "Password Change": "Alteração de password",
//     "Logs": "Logs",
//     "Horizon": "Horizonte",
//     "Languages": "Línguas",
//     "Set commission": "Definir comissão",
//     "Commission (%)": "Comissão (%)",
//     "Enter commission in %": "Insira comissão em %",
//     "Looks good!": "Bom aspeto!",
//     "Yes": "Sim",
//     "Cancel": "Cancelar",
//     "No": "Não",
//     "Order Detail": "Detalhes da encomenda",
//     "Item name": "Nome do produto",
//     "Quantity": "Quantidade",
//     "Unit Price": "Preço unitário",
//     "Total": "Total",
//     "Addons": "Extras",
//     "Item Total": "Total do produto",
//     "Service Charge": "Taxa de serviço",
//     "Delivery Charge": "Taxa de entrega",
//     "Sub Total": "Sub-total",
//     "Discount Amount": "Valor do disconto",
//     "Track Order": "Seguir encomenda",
//     "Order Placed": "Encomenda criada",
//     "Track Delivery Man": "Seguir estafeta",
//     "Customer Delivery Info": "Info entrega ao cliente",
//     "Address": "Morada",
//     "Contact Number": "Número de Contacto",
//     "Delivery man\\'s Info": "Info estafeta",
//     "Phone": "Telefone",
//     "Order List": "Lista de Encomendas",
//     "Here goes the order list": "Esta é a lista de encomendas",
//     "Order Code": "Número da encomenda",
//     "Status": "Estado",
//     "Pickup Time": "Hora de recolha",
//     "Restaurant": "Restaurante",
//     "Delivery Time": "Hora de entrega",
//     "Delivery Status": "Status da entrega",
//     "Total Price": "Valor total",
//     "Created At": "Criado a",
//     "Action": "Ação",
//     "Product Category Add\/Edit": "Categoria de produto Adicionar\/Editar",
//     "Category Name": "Nome da categoria",
//     "Select": "Selecionar",
//     "Slug": "Slug",
//     "Icon": "Ícone",
//     "Save": "Gravar",
//     "Reset": "Reiniciar",
//     "Product Category List": "Lista de categorias de produto",
//     "Here goes the product category list": "Esta é a lista de categorias de produto",
//     "All": "Todos",
//     "Product Add\/Edit": "Adicionar\/Editar produto",
//     "Product List": "Lista de produtos",
//     "Create New Product": "Criar novo produto",
//     "Basic": "Info básica",
//     "Pricing & Options": "Opções e preços",
//     "Gallery": "Galeria",
//     "Reviews": "Avaliações",
//     "Addon Add\/Edit": "Adicionar\/Editar extras",
//     "Name": "Nome",
//     "Price": "Preço",
//     "Description": "Descrição",
//     "Addon List": "Lista de extras",
//     "Here goes the addon list": "Esta é a lista de addon",
//     "Product Name": "Nome do produto",
//     "Category": "Categoria",
//     "Select Cuisines": "Selecionar cozinhas",
//     "Select Supplements": "Selecionar suplementos",
//     "Active Status": "Estado ativo",
//     " Save": "Guardar",
//     "Featured Image": "Imagem de destaque",
//     "Short Description": "Descrição curta",
//     "Full Description": "Descrição longa",
//     " Upload": "Carregar",
//     "Option Name": "Nome da opção",
//     " Add more options": "Adicionar mais opções",
//     "Name can\\'t be empty.": "Nome não pode estar vazio",
//     "Price can\\'t be empty.": "Preço não pode estar vazio",
//     "Price must be greater than 0.": "O preço deve ser superior a 0",
//     "Here goes the product list": "Esta é a lista de produtos",
//     "Create Product": "Criar produto",
//     "Image": "Imagem",
//     "Supplement Add\/Edit": "Adicionar\/Editar suplemento",
//     "Supplement Name": "Nome do suplemento",
//     "Supplement List": "Lista do suplemento",
//     "Here goes the supplement list": "Esta é a lista de suplementos",
//     "First Name": "Primeiro nome",
//     "Last Name": "Último nome",
//     "Email": "Email",
//     "Avatar": "Avatar",
//     "Please upload jpg or png file and size should be under 2mb": "Por favor, carregue um ficheiro jpg ou png, o tamanho deve ser menos que 2mb",
//     "Change Password": "Alterar password",
//     "Old Password": "Password antiga",
//     "New Password": "Nova password",
//     "Confirm Password": "Confirmar password",
//     "Profile settings": "Definições do perfil",
//     "Other Settings": "Outras definições",
//     "Not active yet": "Ainda não está ativo",
//     "Name :": "Nome",
//     "Mobile :": "Telemóvel",
//     "Email :": "Email",
//     "Country :": "País",
//     "City :": "Cidade",
//     "State :": "Estado",
//     "Postal Code :": "Código Postal",
//     "Address :": "Morada",
//     "Email Verification:": "Verificação do Email",
//     "Done": "Feito",
//     "Review List": "Lista de avaliações",
//     "Here goes the review list": "Esta é a lista de avaliações",
//     "Reviewer": "Avaliador",
//     "Review": "Avaliação",
//     "Rating": "Rating",
//     "Role Add\/Edit": "Função Ass\/Editar",
//     "Update route list": "Atualizar a lista de rotas",
//     "Generate route list": "Gerar lista de rotas",
//     "Module": "Módulo",
//     "Select module": "Selecionar módulos",
//     "Title": "Título",
//     "Select route": "Selecionar Rota",
//     "Role List": "Lista de funções",
//     "Here goes the role list": "Esta é a lista de funções",
//     "Google map api key": "Chave da google map api",
//     "Max gallery image": "Máximo imagem galerias",
//     "Default commission from shop on per order item total (%)": "Comissão da loja predefinida por encomenda no total de cada item (%)",
//     "Delivery charge per KM (€)": "Custo de entrega por KM (€)",
//     "Service charge (€)": "Custo de serviço (€)",
//     "Radius distance to search for delivery man (in KM)": "Raio de pesquisa por lojas, a partir da localização do cliente",
//     "Firebase Key": "Chave Firebase",
//     "Looks sdfdsfsdf good!": "Tem bom aspeto!",
//     "Looks bad!": "Tem mau aspeto!",
//     "App logo large": "App logo grande",
//     "App logo small": "App logo pequeno",
//     "Favicon": "Favicon",
//     "Logo saved successfully.": "Logo guardado com sucesso.",
//     "Logo saved failed.": "Guardar logo sem sucesso.",
//     "Application title": "Título da aplicação",
//     "Contact Email": "Email de contacto",
//     "Contact number": "Número de contacto",
//     "Copyright text": "Texto de Direitos de Autor",
//     "About us": "Sobre nós",
//     "Facebook": "Facebook",
//     "Twitter": "Twitter",
//     "Instagram": "Instagram",
//     "Google": "Google",
//     "LinkedIn": "LinkedIn",
//     "Whatsapp": "Whatsapp",
//     "Shop Category Add\/Edit": "Categoria de compra Adicionar\/Editar",
//     "Shop Category List": "Lista de categorias de compra",
//     "Here goes the shop category list": "Esta é a lista de categorias de compra",
//     "Cuisine Add\/Edit": "Cozinha Adicionar\/Editar",
//     "Cuisine Name": "Nome cozinha",
//     "Cuisine List": "Lista de cozinha",
//     "Here goes the cuisine list": "Esta é a lista da cozinha",
//     "Shop Add\/Edit": "Adicionar\/Editar Loja",
//     "Shop List": "Lista de lojas",
//     "Create New Shop": "Criar uma loja nova",
//     "Contact Address": "Endereço de contacto",
//     "Schedule": "Horário",
//     "Holidays": "Férias",
//     "Meta Information": "Informação Meta ",
//     "Social link": "Link social",
//     "Shop Name": "Nome da loja",
//     "Sub Categories": "Sub-categorias",
//     "IBAN": "IBAN",
//     "Bank Identification Number": "Número de conta bancária",
//     "Can\\'t change status until you set correct address with lat and long": "Não é possível alterar o estado até que corrija a morada com a latitude e longitude",
//     "Latitude": "Latitude",
//     "Longitude": "Longitude",
//     "Country": "País",
//     "State": "Distrito",
//     "City": "Cidade",
//     "Postal Code": "Código postal",
//     "Go to Current Location": "Ir para a localização atual",
//     "Add Holidays": "Adicionar férias",
//     "Select Holidays": "Selecionar férias",
//     "Holiday List": "Lista de feriados",
//     "Here goes the holiday list": "Esta é a lista de feriados",
//     "Date": "Data",
//     "Meta Title": "Título Meta",
//     "Meta Keywords": "Palavras-chave Meta",
//     "Meta Descriptions": "Descrições Meta",
//     "Facebook Meta Title": "Título Meta Facebook",
//     "Facebook Meta Keywords": "Palavras-chave Meta Facebook",
//     "Facebook Meta Descriptions": "Descrições Meta Facebook",
//     "Twitter Meta Title": "Título Meta Twitter",
//     "Twitter Meta Keywords": "Palavras-chave Meta Twitter",
//     "Twitter Meta Descriptions": "Descrições Meta Twitter",
//     " Save Meta Information": "Guardar informação Meta",
//     "Days": "Dias",
//     "Weekend": "Fim de semana",
//     "Opening": "Abertura",
//     "Break Start": "Fecho intermédio",
//     "Break End": "Abertura intermédia",
//     "Closing": "Encerramento",
//     "Reset": "Redefinir",
//     "Facebook Link": "Link Facebook",
//     "Facebook link": "link Facebook",
//     "Twitter Link": "Link Twitter",
//     "Twitter link": "link Twitter",
//     "Youtube Link": "Link Youtube",
//     "Youtube link": "link Youtube",
//     "Instagram Link": "Link Instagram",
//     "Instagram link": "link Instagram",
//     "Website Link": "Link Website",
//     "Website link": "link Website",
//     "Here goes the shop list": "Aqui pode ver a lista de lojas",
//     "Create Shop": "Criar loja",
//     "Owner": "Responsável",
//     "Owner Phone": "Telefone do responsável",
//     "Commission per order": "Comissão por encomenda",
//     "User Details": "Detalhes do cliente",
//     "Restaurants": "Restaurantes",
//     "Orders": "Encomendas",
//     "Address Map View": "Ver mapa de endereços",
//     "Joined": "Aderiu",
//     "Email Verification": "Verificação de Email",
//     "User Add\/Edit": "Adicionar\/Editar utilizador",
//     "Admin": "Admin",
//     "Shop Manager": "Gestor de Loja",
//     "Role": "Função",
//     "Suspend": "Suspenso",
//     "Block": "Bloquear",
//     "User List": "Lista de utilizadores",
//     "Here goes the user list": "Esta é a lista de utilizadores",
//     "Delivery Commission": "Comissão de entrega",
//     "Enter your email address and we\\'ll send you an email with instructions to reset your password.": "Insira o seu endereço de email e iremos enviar um email com instruções para reset da sua password.",
//     "Email address": "Endereço de email",
//     "Reset Password ": "Redefinir password",
//     "Go to Login": "Ir para o Login",
//     "Email or phone(with +countrycode)": "Email or número de telemóvel (com o +indicativo de país)",
//     "Password": "Password",
//     "Log In": "Log In",
//     "Forgot your password?": "Esqueceu-se da password",
//     "Signup as a Shop Owner": "Entrar como propietário da loja",
//     "Change your password from here.": "Mudar a sua password aqui.",
//     "Enter your first name": "Insira o seu primeiro nome",
//     "Enter your last name": "Insira o seu último nome",
//     "Enter your email": "Insira o seu email",
//     "Type your phone number": "Escreva o seu número de telemóvel",
//     "Enter your password": "Insira a sua password",
//     "Confirm your password": "Confirma a tua password",
//     "Signup": "Iniciar Sessão",
//     "Click here to login": "Carregue aqui para Iniciar Sessão",
//     "Your Password": "A sua Password",
//     "Hello": "Olá",
//     "In order to reset your password please use the following code (For mobile apps only).": "De forma a redifinir a sua password, por favor, utilize o seguinte código (apenas para aplicações móveis).",
//     "Code": "Código",
//     "Or (For web apps only)": "Ou (Apenas para aplicações web)",
//     "Click here to reset password.": "Carregue aqui para redifinir a sua password",
//     "Thanks a lot for being with us.": "Obrigada por estar connosco.",
//     "Verify": "Verifique",
//     "Your Email": "O seu email",
//     "We need to verify your email. In order to verify your email please use the following code.": "Precisamos de verificar o seu email. De forma a verificar o seu email, por favor, utilize o seguinte código.",
//     "Click here to verify.": "Carregue aqui para verificar.",
//     "Delete": "Eliminar",
//     "N\/A": "N\/A",
//     "Sync missing keys": "Sincronizar as chaves em falta",
//     "Credit": "Crédito",
//     "Debit": "Débito",
//     "Reply Sent": "Resposta enviada",
//     "Pickup": "Recolha",
//     "Delivery": "Entrega",
//     "Assign Delivery Man": "Designar estafeta",
//     "Company": "Empresa",
//     "Undefined": "Indefinido",
//     "Send Reply": "Enviar Resposta",
//     "View Records": "Ver Registos",
//     "shop": "Loja",
//     "del": "",
//     "Download": "Descarregar",
//     "Shop is required.": "Loja é obrigatória",
//     "IBAN field is required.": "O campo do IBAN é obrigatório.",
//     "Title required.": "Título obrigatório",
//     "Title can\\'t be more than 100 characters.": "O título não pode ter mais de 100 caracteres.",
//     "Details required.": "Detalhes obrigatórios",
//     "Title can\\'t be more than 500 characters.": "O título não pode ter mais de 500 caracteres.",
//     "IBAN field can not be empty!": "O campo do IBAN não pode estar vazio!",
//     "Password must be minimum 6 character": "A password deve ter no mínimo 6 caracteres.",
//     "Cancel Order": "Cancelar Encomenda",
//     "Actions": "Ações",
//     "Shop can\\'t process your order at your expected delivery time.": "A loja não consegue processar o seu pedido na hora de entrega estimada.",
//     "Invalid delivery man": "Estafeta inválido",
//     "Your request is under processing. Please reload after a while.": "O seu pedido está a ser processado. Por favor, recarregue ao fim de algum tempo.",
//     "Address updated successfully.": "Endereço atualizado com sucesso.",
//     "Address update failed.": "Atualização do endereço sem sucesso.",
//     "First You have to save one option as default.": "Primeiro, tem de guardar uma opção como padrão.",
//     "Can\\'t delete default option.": "Não pode apagar a opção padrão.",
//     "Invalid request": "Pedido inválido",
//     "Issue registered successfully. You will get reply to your account email address.": "Problema registado com sucesso. Irá receber a resposta na sua conta de email.",
//     "Invalid issue.": "Problema inválido.",
//     "Reply sent successfully.": "Resposta enviada com sucesso.",
//     "Sorry!! No user have balance.": "Lamentamos!! O utilizador não tem saldo.",
//     "Amount is ": "O valor é",
//     "All Orders": "Todas as encomendas",
//     "Pending Orders": "Encomendas pendentes",
//     "Accepted Orders": "Encomendas aceites",
//     "Picked Orders": "Encomendas levantadas",
//     "Delivered Orders": "Encomendas entregues",
//     "Rejected Orders": "Encomendas rejeitadas",
//     "Cancelled Orders": "Encomendas canceladas",
//     "Categories": "Categorias",
//     "Products": "Produtos",
//     "Application Settings": "Definições da aplicação",
//     "Site Settings": "Definições do site",
//     "Logo Settings": "Definições de logotipo",
//     "Social Settings": "Definições redes sociais",
//     "Shops": "Lojas",
//     "Support": "Suporte",
//     "Issues": "Ocorrências",
//     "Shop Owners": "Lojistas",
//     "Customers": "Clientes",
//     "Wallet": "Carteira",
//     "Shop Owner Wallets": "Carteira do lojista",
//     "Delivery Man Wallets": "Carteira do estafeta",
//     "Export & Reset Logs": "",
//     "User Management": "Gestão de utilizador",
//     "Wallet Management": "Gestão de carteira",
//     "Register an Issue": "Registar incidente",
//     "Order ": "Encomenda",
//     "----": "",
//     "Submit": "Submeter",
//     "Issue Title": "Título do Problema",
//     "Details": "Detalhes",
//     "Issue Details": "Detalhes do Título",
//     "Message": "Mensagem",
//     "Write something...": "Escreve alguma coisa",
//     "Send": "Enviar",
//     "Delivery Time Info": "Info tempo de entrega",
//     "Income Info": "Info valores",
//     "Order Note": "Nota da encomenda",
//     "Shop Info": "Informação da loja",
//     "Owner\\'s Phone": "Contacto do Proprietário",
//     "Company Commission": "Comissão da Empresa",
//     "Item Total Price": "Preço total do item",
//     "Income": "Rendimento",
//     "Pickup & Delivery Info": "Info recolha e entrega",
//     "Status Info": "Informações sobre o estado",
//     "Is Default?": "Está predefinido?",
//     "System\\'s price per KM (€)": "Valor por KM a cobrar ao cliente",
//     "Price per KM for Delivery Man (€)": "Valor por KM a pagar ao estafeta",
//     "System\\'s service charge (€)": "Custo fixo por encomenda a cobrar ao cliente",
//     "Service charge for Delivery Man (€)": "Custo fixo por encomenda a pagar ao estafeta",
//     "Select Owner": "Proprietário Selecionado",
//     "Balance": "Saldo",
//     "User Email": "Email do utilizador",
//     "Previous Balance": "Saldo anterior",
//     "Type": "Tipo",
//     "Change Amount": "Alterar valor",
//     "Current Balance": "Saldo atual",
//     "Note": "Nota",
//     " Details": "Detalhes",
//     "Balance Records": "Histórico de saldos",
//     "Delivery Info": "Info entrega",
//     " Add\/Edit": "Adicionar\/Editar",
//     "Reset Password (Leave empty if you don\\'t want to change)": "Redefinir Password (deixar vazio se não quer mudar)",
//     " List": "Lista",
//     "Here goes the ": "Aqui vai o",
//     " list": "lista",
//     "File": "Ficheiro",
//     "Total Rows": "Filas totais",
//     "Total Amount": "Montante total",
//     " Wallet List": "Lista da carteira",
//     " Wallet list": "lista da carteira",
//     "Export & Reset": "Exportar & Redefinir",
//     "Last Withdraw": "Último levantamento",
//     "Failed": "Falhado",
//     "Delivery Started": "A entrega começou",
//     "Registered": "Registado",
//     "Expired": "Expirado",
//     "Payment": "Pagamento",
//     "You have to create shop first": "Tem de criar uma loja primeiro",
//     "See nearest delivery men": "Ver o estafeta mais perto",
//     "Set Customer Range": "Definir raio de clientes",
//     "Range should not be greater than ": "O intervalo não deve ser maior que",
//     "Quantity can\\'t be less than 1.": "A quantidade não pode ser menor que 1.",
//     "Social User ID required.": "ID Social do Utilizador obrigatório.",
//     "Phone can\\'t be empty.": "O telemóvel não pode estar vazio.",
//     "Profile Photo must be an image!": "Foto de perfil deve ser uma imagem!",
//     "Profile Photo file must be of type jpg, jpeg, png!": "O ficheiro da foto de perfil deve ser em tipo jpg, jpeg, png!",
//     "Profile Photo file must be less than 2MB!": "o ficheiro da foto de perfil deve ter menos de 2MB!",
//     "Invalid User.": "Utilizador inválido.",
//     "Logged in successfully!": "Login efetuado com sucesso!",
//     "Wrong credentials!": "Credenciais erradas!",
//     "Cart empty succeeded.": "Carrinho esvaziado com sucesso.",
//     "Product addons added to cart successfully.": "Addons do produto adicionado ao carrinho com sucesso.",
//     "You have new order to accept.": "Tem uma encomenda nova para aceitar.",
//     "New Order": "Nova encomenda",
//     "You have a new order": "Tem uma encomenda nova",
//     "Status of Your Order": "Estado da sua encomenda",
//     "is": "é",
//     "Order Update": "Atualização na sua encomenda",
//     "Delivery Status of Your Order": "Estado de entrega da sua encomenda",
//     "Order Payment": "Pagamento da encomenda",
//     "Payment Status of Your Order": "Estado do pagamento da sua encomenda",
//     "Delivery Acceptation Expired of Order": "Aceitação da entrega da encomenda expirada",
//     "Invalid order.": "Encomenda inválida.",
//     "Already reviewed.": "Já foi avaliado.",
//     "Review added successfully.": "Avaliação adicionada com sucesso.",
//     "Order total can\\'t be 0.00": "O total da encomenda não pode ser 0.00",
//     "Sorry! The order has been cancelled by admin.": "Lamentamos! A sua encomenda foi cancelada pelo admin.",
//     "Sorry! Acceptation expired.": "Lamentamos! A aceitação expirou.",
//     "Declined successfully.": "Recusado com sucesso.",
//     "Sorry! The order has been cancelled.": "Lamentamos! A encomenda foi cancelada.",
//     "Delivery accept duration expired.": "Duração de aceitação da entrega expirada.",
//     "You are assigned to order:": "Está atribuído para esta encomenda",
//     "Order Assigned": "Encomenda atribuída",
//     "Finish the payment quickly.": "Termine o pagamento rapidamente.",
//     "Payment completed successfully.": "Pagamento concluído com sucesso.",
//     "Amount mismatch.": "Quantia não correspondente.",
//     "Address deleted successfully.": "Endereço eliminado com sucesso.",
//     "Address delete failed.": "Eliminação do endereço sem sucesso.",
//     "Invalid address": "Endereço inválido.",
//     "Set another address as default first.": "Defina outro endereço como padrão primeiro.",
//     "Phone number already used by another user.": "Número de telemóvel já utilizado por outro utilizador.",
//     "Address saved successfully.": "Endereço guardado com sucesso.",
//     "Social logged in users can\\'t do this.": "Utilizadores que fizeram loggin com as redes sociais não podem fazer esta ação.",
//     "Can\\'t make sub categories.": "Não pode fazer subcategorias.",
//     "Group has been created successfully.": "O grupo foi criado com sucesso.",
//     "Group create failed.": "Criação do grupo sem sucesso.",
//     "Group has been updated successfully": "Atualização do grupo com sucesso.",
//     "Group deleted successfully.": "Grupo eliminado com sucesso.",
//     "Group delete failed.": "Eliminação do grupo sem sucesso.",
//     "Delivery man assigned successfully.": "Estafeta atribuído com sucesso.",
//     "Customer Range set successfully.": "Raio de clientes definido com sucesso.",
//     "Saved successfully.": "Guardado com sucesso.",
//     "Save failed.": "Falha ao guardar.",
//     "User has been created successfully. Initial Password: 123456": "O utilizador foi criado com sucesso. Password inicial: 123456",
//     "Address save failed.": "Falha ao guardar o endereço.",
//     "Total Income": "Rendimento total",
//     "Wallet Balance": "Balanço da Carteira",
//     "Total Users": "Total de Utilizadores",
//     "Delivery Men": "Estafeta",
//     "Total Withdraw": "Total de levantamento",
//     "Total Sale": "Total de vendas",
//     "Total Orders": "Total encomendas",
//     "Total Products": "Total produtos",
//     "Groups": "Grupos",
//     "Shop ": "Loja",
//     "Range Radius (Km)": "Intervalo de Raio (km)",
//     "Special Request": "Pedido especial",
//     "Payment Info": "Info pagamento",
//     "Paid Amount": "Valor pago",
//     "Payment By": "Pagamento por",
//     "Payment Id": "Identificação do Pagamento",
//     "Dont\\'t type the countrycode with the number": "Não digite o indicativo do país com o número",
//     "Radius distance to search for shops from customer location (in KM)": "Raio de distância para pesquisar pela localização do cliente (em KM)",
//     "Payment expiration time in Minute": "Tempo para expirar pagamento (em minutos)",
//     "Delivery accept duration in Minute": "Tempo de aceitação da entrega em minutos",
//     "How many days to show for order?": "Quantos dias para mostrar a encomenda?",
//     "Group Add\/Edit": "Adiciona\/Editar Grupo",
//     "Group Name": "Nome Grupo",
//     "Group List": "Lista do Grupo",
//     "Here goes the group list": "Esta é a lista do grupo",
//     "Contact & Address": "Contacto & Endereço",
//     "Group": "Grupo",
//     "Nearest Delivery Man List": "Lista de Estafetas mais perto ",
//     "Distance": "Distância",
//     "Km": "Km",
//     "No data available.": "Não há dados disponíveis.",
//     "Here goes the balance record list": "Esta é a lista de balanços registados",
//     "Logged in by ": "Entrou por",
//     "Profile Photo": "Foto de perfil",
//     "Payment|Multibanco": "Pagamento|Multibanco",
//     "Payment by ATM or Homebanking": "Pagamento por ATM ou Homebanking",
//     "Fractional payment for exceeding the limit value for payments in the Multibanco system": "Pagamento fracionado por exceder o valor limite de pagamento no sistema de Multibanco",
//     "Entity": "Identidade",
//     "Reference": "Referência",
//     "Value": "Valor",
//     "Validity": "Validade",
//     "The receipt issued by the ATM is proof of payment. Keep it.": "O recibo emitido pelo ATM é o comprovativo de pagamento. Guarde-o.",
//     "Caution: Do not reload this page.": "Cuidado: Não recarregue esta página.",
//     "Proceed": "Prosseguir",
//     "Redirect Payment": "Redirecionar o pagamento",
//     "Upload unsuccessful": "Carregamento sem sucesso",
//     "Nothing available.": "Nada disponível.",
//     "No cart item found": "Não foram encontrados items no carrinho",
//     "Image must be less than or equal ": "A imagem dever menor ou igual a",
//     "Image width and height must be less than or equal ": "A largura e altura da imagem deve ser menor ou igual a",
//     "Image required.": "Imagem obrigatória.",
//     "Status required.": "Estado obrigatório.",
//     "Invalid image format.": "Formato da imagem inválido.",
//     "Image max size 2MB exceed.": "Tamanho máximo da imagem excede os 2MB.",
//     "NIF can not be empty!": "NIF não pode estar vazio!",
//     "NIF field can not be empty!": "O campo NIF não pode estar vazio!",
//     "Password should be minimum 6 characters!": "A password deve conter no mínimo 6 caracteres!",
//     "Confirm Password doesn\\'t match!": "A password confirmada não corresponde!",
//     "Try with your social login.": "Tente o seu login social.",
//     "Social logged in user can\\'t do it.": "Utilizador com login das redes sociais não pode fazer isso.",
//     "Added to cart successfully.": "Adicionado ao carrinho com sucesso",
//     "Cart updated successfully.": "Carrinho atualizado com sucesso",
//     "Item deleted from cart successfully.": "Artigo apagado do carrinho com sucesso.",
//     "No default delivery address found of the customer.": "Não foi encontrado nenhum endereço padrão do cliente.",
//     "Slider has been created successfully.": "Slider foi criado com sucesso.",
//     "Slider create failed.": "Criação do slider sem sucesso.",
//     "Slider has been updated successfully": "Slider atualizado com sucesso",
//     "Slider deleted successfully.": "Slider eliminado com sucesso.",
//     "Slider delete failed.": "Eliminação do slider sem sucesso.",
//     "Slider Settings": "Configurações dos sliders",
//     "Item": "Artigo",
//     "Addon": "Extra",
//     "Bonus Added ": "Bónus adicionado",
//     "No bonus added": "Não foi adicionado nenhum bónus",
//     "Delivered on time": "Entregue a tempo",
//     "Delivery not on time": "Não entregue a tempo",
//     "Max Size": "Tamanho máximo",
//     "Width": "Largura",
//     "Height": "Altura",
//     "To resize go to ": "Para redimensionar vai para",
//     "NIF": "NIF",
//     "NIF :": "NIF",
//     "Home slider image transition time in seconds": "Tempo transição do slider em segundos",
//     "Delivery on time bonus for Delivery Man (%)": "Bonus estafeta por entrega a tempo (%)",
//     "How many days to show for order timeslot?": "Permissão de encomendar até X dias para a frente",
//     "Help Text": "Texto de Ajuda",
//     "Slider Add\/Edit": "Adicionar\/Editar Slider",
//     "Link": "Link",
//     "Slider List": "Lista de Slider",
//     "Here goes the slider list": "Esta é a lista de slider",
//     "Order Delivery": "Entrega de encomenda",
//     "Time slot start gap for current day in minute": "Tempo (minutos) de desfasamento",
//     "Order not found.": "Encomenda não encontrada.",
//     "Home Address saved successfully.": "Endereço da residência guardado com sucesso.",
//     "Home Address save failed.": "Falha ao guardar endereço da residência.",
//     "User Note saved successfully.": "Nota do utilizador guardada com sucesso.",
//     "User Note save failed.": "Falha ao guardar a nota do utilizador.",
//     "Document saved successfully.": "Documento guardado com sucesso.",
//     "Document Deleted successfully.": "Documento eliminado com sucesso.",
//     "Crop the Image": "Cortar a Imagem",
//     "Crop Image": "Cortar Imagem",
//     "Terms & Condition Link": "Link Termos e Condições",
//     "Terms and conditions": "Termos e Condições",
//     "Comments": "Comentários",
//     "Documents": "Documentos",
//     "Document Name": "Nome do Documento",
//     "Upload Documents": "Carregar Documentos",
//     " Add Documents": "Adicionar Documentos",
//     "Home Address": "Endereço de residência",
//     "Home Postal Code": "Código Postal de residência",
//     "Home City": "Cidade de residência",
//     "Notes": "Notas",
//     "Vehicle Type": "Tipo de veículo",
//     "Are you sure to download \".roles($role).\" List as .CSV format?": "Tem a certeza que quer fazer download \".roles($role).\" List as .CSV format?",
//     "Export": "Exportar",
//     "Your :order_code Order Delivery Time has been Updated to :expected_delivery_time" : "Sua :order_code O tempo de entrega do pedido foi atualizado para :expected_delivery_time",
//     "Order Time Update" : "Tempo da Encomenda atualizado",
//     "Restaurant failed to response in 5 minutes" : "Restaurante não respondeu em 5 minutos",
//     "Hello Group Manager" : "Olá Gestor do Grupo",
//     "An order with ID - :order_code has been delayed over 5 minutes to be accepted by :restaurant restaurant." : "Uma encomenda com a identificação - :order_code foi adiada mais de 5 minutos a ser aceite pelo :restaurant restaurant.",
//     "Please take a relevant step to notify the restaurant." : "Por favor, tome um passo relevante para notificar o restaurante.",
//     " Delivery time" : " tempo de entrega",
//     "Tax ID" : "Tax ID",
//     "Tax Identification Number": "Número de Identificação Fiscal",
//     "Tax ID field is required.": "O campo do Tax ID é obrigatório.",
//     "Account deleted successfully." :  "Conta eliminado com sucesso.",
//     "Account delete failed." : "Eliminação do Conta sem sucesso.",
//     " Sales Report" : " Relatório de vendas",
//     "Here goes the Restaurants" : "Aqui vai os Restaurantes"
// }

